POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
    "email": "swagata@yopmail.com",
    "password": ".i!z0pA$Y87J"
}

####

POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
    "fullname": "Swagata Das",
    "email": "swagata@yopmail.com",
    "password": "Chatter@24",
    "phone": "9101004426",
    "address": "Haldia, Kolkata, West Bengal"
}

####

GET http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhmZDlmMTUyYzIwZDUzZTc1NjkyMzYiLCJlbWFpbCI6ImJpcmFqQHlvcG1haWwuY29tIiwiaWF0IjoxNzIxODk4NjQyLCJleHAiOjE3MjE5MDA0NDJ9.xULKwVCzHfZQoIXaGRHWHP8euJfollARoz9haNpDnrs

###

POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
    "email": "swagata@yopmail.com"
}

###

GET http://localhost:3000/friends/profile/66a0c8804b30a4a19cba945e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmEwYmMyYTEwNjg5YmY4ZWNmZTE2NDYiLCJlbWFpbCI6ImFua2FuYUB5b3BtYWlsLmNvbSIsImlhdCI6MTcyMTkwMzY1NSwiZXhwIjoxNzIxOTA1NDU1fQ.hsUkfBFUl_1pM8yME3eJlkCe1vqHL3shxY1WhwhGW30

###


GET http://localhost:3000/friends/suggested
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhmZDlmMTUyYzIwZDUzZTc1NjkyMzYiLCJlbWFpbCI6ImJpcmFqQHlvcG1haWwuY29tIiwiaWF0IjoxNzIxOTA2MDUxLCJleHAiOjE3MjE5MDc4NTF9.gWJyPxJs0V4MGfYmxre3qiNBoODoBvSgbYmgqnduLxI

###

GET http://localhost:3000/friends/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhmZDlmMTUyYzIwZDUzZTc1NjkyMzYiLCJlbWFpbCI6ImJpcmFqQHlvcG1haWwuY29tIiwiaWF0IjoxNzIxOTA5Njk1LCJleHAiOjE3MjE5MTE0OTV9._32ViVzQsN_rvCm341JPbuxbhrGgg1SZ_fQG9adL6q0

###

POST http://localhost:3000/friends/add-friend
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhmZDlmMTUyYzIwZDUzZTc1NjkyMzYiLCJlbWFpbCI6ImJpcmFqQHlvcG1haWwuY29tIiwiaWF0IjoxNzIxOTA2MDUxLCJleHAiOjE3MjE5MDc4NTF9.gWJyPxJs0V4MGfYmxre3qiNBoODoBvSgbYmgqnduLxI

{
    "friendId": "66a0bc2a10689bf8ecfe1646"
}

###

POST  http://localhost:3000/friends/remove-friend
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhmZDlmMTUyYzIwZDUzZTc1NjkyMzYiLCJlbWFpbCI6ImJpcmFqQHlvcG1haWwuY29tIiwiaWF0IjoxNzIxOTA2MDUxLCJleHAiOjE3MjE5MDc4NTF9.gWJyPxJs0V4MGfYmxre3qiNBoODoBvSgbYmgqnduLxI

{
    "friendId": "66a0bc2a10689bf8ecfe1646"
}

###

GET http://localhost:3000/friends/friend-requests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhmZDlmMTUyYzIwZDUzZTc1NjkyMzYiLCJlbWFpbCI6ImJpcmFqQHlvcG1haWwuY29tIiwiaWF0IjoxNzIxOTA2MDUxLCJleHAiOjE3MjE5MDc4NTF9.gWJyPxJs0V4MGfYmxre3qiNBoODoBvSgbYmgqnduLxI

###

PUT http://localhost:3000/friends/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhmZDlmMTUyYzIwZDUzZTc1NjkyMzYiLCJlbWFpbCI6ImJpcmFqQHlvcG1haWwuY29tIiwiaWF0IjoxNzIxOTA2MDUxLCJleHAiOjE3MjE5MDc4NTF9.gWJyPxJs0V4MGfYmxre3qiNBoODoBvSgbYmgqnduLxI

{
    "friendId": "66a0bc2a10689bf8ecfe1646",
    "isFollowing": true
}

###

POST http://localhost:3000/friends/friend-search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhmZDlmMTUyYzIwZDUzZTc1NjkyMzYiLCJlbWFpbCI6ImJpcmFqQHlvcG1haWwuY29tIiwiaWF0IjoxNzIxOTA5Njk1LCJleHAiOjE3MjE5MTE0OTV9._32ViVzQsN_rvCm341JPbuxbhrGgg1SZ_fQG9adL6q0

{
    "query": "ankana"
}